import { Request } from "express"
import { UPLOAD_DIR } from "../middleware/upload.middleware.js";

class Utils {
    /**
    * Extracts the relative path from an absolute path generated by Multer.
    * Example:
    *   D:\project\uploads\image-xxx.jpg  -->  /uploads/image-xxx.jpg
    *
    * @param {string} fullPath - The full file path.
    * @returns {string} - The relative path starting with /uploads/...
    */
    static extractUploadRelativePath(fullPath: string) {
        if (!fullPath) return "";

        // Normalize separators to support both Windows and Linux
        const normalizedPath = fullPath.replace(/\\/g, "/");

        // Find the position of the "uploads" directory
        const uploadsIndex = normalizedPath.indexOf(UPLOAD_DIR);

        // If "uploads" is not found, return the normalized path
        if (uploadsIndex === -1) return normalizedPath;

        // Extract starting from "/uploads/"
        return normalizedPath.substring(uploadsIndex);
    }

    /**
     * Builds the full (public) URL of an uploaded file.
     * Example:
     *   (req, '/uploads/image-xxx.jpg') --> http://localhost:3000/uploads/image-xxx.jpg
     *
     * @param {object} req - The Express Request object (used to get host and protocol).
     * @param {string} relativePath - The file's relative path (e.g. /uploads/xxx.jpg).
     * @returns {string} - The full file URL.
     */
    static buildFullFileUrl(req: Request, relativePath: string) {
        if (!relativePath) return "";

        if (
            relativePath.startsWith("http://") ||
            relativePath.startsWith("https://") ||
            relativePath.startsWith("data:")
        ) {
            return relativePath;
        }

        const protocol = req.protocol;
        const host = req.get("host");

        return `${protocol}://${host}${relativePath}`;
    }

    static getRandomNumber(min: number, max: number) {
        return Math.floor(Math.random() * (max - min) + min);
    }
}

export default Utils;